deliriummcore/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'ticket', views.TicketViewSet)
router.register(r'entrada', views.EntradaViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls'))
]

deliriummcore/deliriummcore/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("core/", include("core.urls")),
    path("events/", include("events.urls")),
    path("oldcore/", include("oldcore.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

deliriummcore/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path("", views.landingPage, name="landingPage"),
    path("home/", views.home, name="home"),
    path("events/", views.events, name="events"),
    path("wallet/", views.wallet, name="wallet"),
    path("places/", views.places, name="places"),
    path("profile/", views.profile, name="profile"),

]

deliriummcore/oldcore/urls.py
from django.urls import path

from . import views

app_name = 'oldcore'

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),

    path("a/", views.admin_index, name="admin_index"),
    path("a/lista_requests/", views.admin_lista_requests, name="admin_lista_requests"),
    path("a/rp_check/select", views.rp_check_select, name="rp_check_select"),
    path("a/rp_check/<str:username>", views.rp_check_main, name="rp_check_main"),
    path("a/cash/", views.cash_index, name="cash_index"),
    path("a/cash/cashpaytoggle/<int:id>", views.cashpaytoggle, name="cashpaytoggle"),

    path('a/log_websocket/<str:room_name>/', views.log_websocket, name='log_websocket'),

    path("r/new/", views.create_request, name="create_request"),
    path("r/new/create", views.new_ticket_request, name="new_ticket_request"),
    path("r/<int:requestid>", views.request_view, name="request_view"),

    path("r/my_requests", views.my_requests, name="my_requests"),
    path("r/my_requests/list", views.lista_requests, name="lista_requests"),

    path("r/<int:requestid>/delete", views.delete_ticket_request, name="delete_ticket_request"),
    path("a/<int:requestid>", views.admin_request_view, name="admin_request_view"),
    path("a/<int:requestid>/ap", views.aprobar_request, name="aprobar_request"),
    path("a/<int:requestid>/re", views.rechazar_request, name="rechazar_request"),
    path("a/<int:requestid>/ar", views.archivar_request, name="archivar_request"),
    path("a/<int:requestid>/as", views.asignar_request, name="asignar_request"),
    path("t/export/<str:hash>", views.temp_ticket_export, name="temp_ticket_export"),
    path("t/requestall/<str:requestid>", views.image_tickets, name="image_tickets"),
    path("t/image/<str:hash>", views.image_ticket, name="image_ticket"),
    path("t/download/<str:tickethash>", views.download_ticket, name="download_ticket"),
]

deliriummcore/oldcore/models.py
from datetime import datetime
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Seller(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    
    class Meta:
         
        permissions = (
            ("can_view_admin", "To see admin pages"),
            ("can_view_staff", "To see staff pages"),
            ("can_view_rp", "To see rp PAGES"),
        )


class Event(models.Model):
    name = models.CharField(verbose_name="Nombre", max_length=30)
    datetime = models.DateTimeField()
    locationmapslink = models.CharField(max_length=300, verbose_name="Google Maps Link", blank=True)

    STATUS = ( 
        ("AN", "Anunciado"), 
        ("EV", "En Venta"), 
        ("VT", "Venta Terminada"), 
        ("AR", "Archivado"), 
    ) 
    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default='AN',
    )

    def __str__(self) -> str:
        return self.name

class Fase(models.Model):
    name = models.CharField(verbose_name="Nombre de Fase", max_length=20)
    event = models.ForeignKey(verbose_name="Evento", to=Event, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name="Precio")
    is_active = models.BooleanField(default=False)
    q_sells = models.IntegerField(verbose_name="Ventas", default=0)

    def __str__(self):
        return "Fase - " + self.name + " - " + self.event.name
    


class TicketRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    seller = models.ForeignKey(to=Seller, on_delete=models.CASCADE)
    event = models.ForeignKey(to=Event, on_delete=models.CASCADE)
    context = models.CharField(max_length=300, blank=True)
    q_tickets = models.IntegerField(verbose_name="Tickets")
    reference = models.CharField(max_length=150, default="none")
    client = models.CharField(max_length=50, default="none")
    fase = models.ForeignKey(Fase, on_delete=models.CASCADE)
    total = models.IntegerField(verbose_name="Total", default="0")
    created = models.DateTimeField(auto_now=True)
    staff_asigned = models.CharField(max_length=30, default="none")
    comprobante = models.FileField(upload_to='uploads/comprobantes/quimera/', blank=True)

    PAYMENTS = ( 
        ("CASH", "Efectivo"), 
        ("TRANSFER", "Transferencía"), 
        ("DEPOSIT", "Deposíto"), 
    ) 
    payment_method = models.CharField(
        max_length=20,
        choices=PAYMENTS,
        default='CASH',
    )

    STATUS = ( 
        ("PE", "Pendiente"), 
        ("RE", "Rechazado"), 
        ("AP", "Aprobado"), 
        ("AR", "Archivado"), 
    ) 
    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default='PE',
    )

    cash_pay = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return "#" + str(self.pk) + " - " + self.user.username + " " + self.status 



class Ticket(models.Model):

    hash = models.CharField(primary_key=True, verbose_name="Hash Id", max_length=200)
    client = models.CharField(max_length=50, default="none")
    ticketrequest = models.ForeignKey(TicketRequest, on_delete=models.CASCADE)


    user = models.ForeignKey(User, on_delete=models.CASCADE)
    seller = models.ForeignKey(to=Seller, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    fase = models.ForeignKey(Fase, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name="Price")

    status_export = models.BooleanField(default=True)

    use = models.BooleanField(default=False)
    
    def __str__(self):
        return "%s %s" % (self.hash, self.ticketrequest.pk)

class CommentTicketRequest(models.Model):
    ticketrequest = models.ForeignKey(TicketRequest, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    text = models.CharField(max_length=600)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)


class RegToken(models.Model):
    token = models.CharField(max_length=20)

class Entrada(models.Model):
    name = models.CharField(max_length=40, default="name_default")
    price = models.IntegerField(verbose_name="Price")
    created = models.DateTimeField(auto_now=True)
    isCortesia = models.BooleanField(default=False)
    

    def __str__(self):
        return str(self.price) + "$ - " + str(self.isCortesia)
    
    

deliriummcore/oldcore/templates/oldcore/admin_index.html
{% extends "oldcore/base.html"%}

{% block title %}Dashboard ADMIN - DLMM{% endblock %}

{% block content %}



<div class="container-fluid">
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        <h1>Admin</h1>
        <p>Hola {{ user.username }}!</p>
        
        <div class="container mt-3">
            <h2>Herramientas</h2>
        </div>


        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-xl-4">

                <div class="col p-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Lista Requests</h5>
                            <a href="{% url 'oldcore:admin_lista_requests' %}" class="card-link">Entrar</a>
                        </div>
                    </div>
                </div>

                <div class="col p-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">RP Check</h5>
                            <a href="{% url 'oldcore:rp_check_select' %}" class="card-link">Entrar</a>
                        </div>
                    </div>
                </div>

                <div class="col p-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Log WebSocket</h5>
                            <a href="{% url 'oldcore:log_websocket' 'default' %}" class="card-link">Entrar</a>
                        </div>
                    </div>
                </div>

                <div class="col p-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Manejo de Efectivo</h5>
                    
                    
                            <a href="{% url 'oldcore:cash_index' %}" class="card-link">Entrar</a>
                        </div>
                    </div>
                </div>


                <div class="col p-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Comisiones</h5>
                            <a href="" class="card-link">Entrar</a>
                        </div>
                    </div>
                </div>



            </div>
        </div>

    </div>


    
</div>



{% endblock %}

deliriummcore/oldcore/templates/oldcore/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}OLD Core{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">


    {% block head %}

    {% endblock %}



</head>

<body>
    <header>
        <nav class="navbar navbar-light bg-light navbar-expand-md justify-content-center shadow-sm pb-3 mb-5">

            <div class="container">

                <a href="{% url 'oldcore:index' %}" class="navbar-brand d-auto w-50 me-auto">
                    OldCORE
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
                    <ul class="navbar-nav w-100 justify-content-center">
                    
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'oldcore:index' %}">
                                <img class="mx-auto d-none d-sm-block" src="{% static 'core/icons/house_fill_black.svg'%}" width="20px" height="20px" alt="">
                                Inicio
                            </a>
                        </li>

                        <li class="nav-item active">
                            <a class="nav-link" src="{% static 'main/calendar_white.svg'%}" href="{% url 'oldcore:dashboard' %}">
                                <img class="mx-auto d-none d-sm-block" src="{% static 'core/icons/hammer_fill_black.svg'%}" width="20px" height="20px" alt="">
                                Dashboard
                            </a>
                        </li>
                        



                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            
                            <img class="mx-auto d-none d-sm-block" src="{% static 'core/icons/d_square_fill_black.svg'%}" width="20px" height="20px" alt="">

                            Core Old
                                


                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarScrollingDropdown">
                                <li><a class="dropdown-item" href="{% url 'oldcore:create_request' %}">Crear Request</a></li>
                                <li><a class="dropdown-item" href="{% url 'oldcore:my_requests' %}">Ver mis Requests</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'oldcore:admin_index' %}">Admin</a></li>
                            </ul>
                        </li>



                        <li class="nav-item active">
                            <a class="nav-link" src="{% static 'main/calendar_white.svg'%}" href="{% url 'oldcore:admin_index' %}">
                                <img class="mx-auto d-none d-sm-block" src="{% static 'core/icons/a_square_black.svg'%}" width="20px" height="20px" alt="">
                                Admin
                            </a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" target="_blank" rel="noopener" href="https://api.whatsapp.com/send?phone=5215532110237&text=Necesito%20ayuda%20con%20DLMM%20OldCore!">
                                <img class="mx-auto d-none d-sm-block" src="{% static 'core/icons/questionmark_circle_fill_black.svg'%}" width="20px" height="20px" alt="">
                                Support
                        </a>
                        </li>

                    </ul>
                    
                    <ul class="nav navbar-nav ms-auto w-100 justify-content-end">

                        {% comment %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Right</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Right</a>
                        </li>
                        {% endcomment %}

                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">

                            <img class="d-block d-sm-none" src="{% static 'core/icons/person_crop_circle_black.svg'%}" width="20px" height="20px" alt="">

                            
                            <img class="mx-auto d-none d-sm-block" src="{% static 'core/icons/person_crop_circle_black.svg'%}" width="20px" height="20px" alt="">

                            {{ user.username }}
                                


                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarScrollingDropdown">
                                <li><a class="dropdown-item" href="">Perfil</a></li>
                                <li><a class="dropdown-item" href="#">Configuración</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'main:home' %}">Salir de OldCore</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            
        </nav>
        
        
    </header>

    <div class="container">
        {% if message %}
            {% if message_type %}
            <div class="alert alert-{{ message_type }}" role="alert">
               {{ message }}
              </div>
            {% endif %}
        {% endif %}
        
        {% block content %}
        {% endblock %}
    </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

deliriummcore/oldcore/templates/oldcore/dashboard.html
{% extends "oldcore/base.html"%}

{% block title %}Dashboard - DLMM{% endblock %}

{% block content %}



<div class="container-fluid">
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        <h1>Dashboard</h1>
        <p>Hola {{ user.username }}!</p>
        
        <div class="card shadow mb-4 ">
            <div class="card-body ">
                <ul class="nav justify-content-center">
                  
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'oldcore:create_request' %}">Crear Request</a>
                    </li>
                    <a class="nav-link" href="{% url 'oldcore:my_requests' %}">Ver mis Requests</a>
                    </li>
                </ul>
            </div>
        </div>


        <div class="container mt-3">
            <h2>Herramientas</h2>
        </div>


        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-xl-4">

                <div class="col p-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Manejo de Efectivo</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Faltante: {{ debt_cash }} MXN</h6>
                            <h6 class="card-subtitle mb-2 text-muted">Total: {{ all_cash }} MXN</h6>
                            <h6 class="card-subtitle mb-2 text-muted">Pagado: {{ paid_cash }} MXN</h6>
                    
                    
                            <a href="" class="card-link">Entrar</a>
                        </div>
                    </div>
                </div>

                <div class="col p-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Mis Ventas</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Vendido: {{ ap_cash }} MXN</h6>
                            <h6 class="card-subtitle mb-2 text-muted">Boletos: {{ boletos }}</h6>
                            <a href="" class="card-link">Entrar</a>
                        </div>
                    </div>
                </div>

                <div class="col p-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Comisiones</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Vendido: {{ ap_cash }} MXN</h6>
                            <h6 class="card-subtitle mb-2 text-muted">Comisión: {{ comision }} MXN</h6>
                            <a href="" class="card-link">Entrar</a>
                        </div>
                    </div>
                </div>



            </div>
        </div>

    </div>


    
</div>



{% endblock %}

deliriummcore/oldcore/templates/oldcore/image_tickets.html
<!DOCTYPE html>
<html lang="en">
    <head>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style>
            .col{
                text-align: center;
            }
            .row{
                text-align: center;
            }
            h6{
                font-size: small;
            }
            h1{
                text-align: center;
            }
        </style>

    </head>
    <body>
        <div class="container">
            <h1>Ticket</h5>
        </div>

        <div class="row">
            <h5>#{{ ticket.hash }}</h1>
            <img src="/media/tickets/{{ ticket.hash }}.jpg" />
            <a href="{% url 'oldcore:download_ticket' ticket.hash %}">Descargar como Archivo</a> 
            <h1>------------------------------------------</h1>
        </div>
        
    </body>
</html>

deliriummcore/oldcore/templates/oldcore/image_tickets_request.html
<!DOCTYPE html>
<html lang="en">
    <head>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style>
            .col{
                text-align: center;
            }
            .row{
                text-align: center;
            }
            h6{
                font-size: small;
            }
            h1{
                text-align: center;
            }
        </style>

    </head>
    <body>
        <div class="container">
            <h1>Request #{{requestid}}</h5>
        </div>

        {% for ticket in  tickets %}
        <div class="row">
            <h5>#{{ ticket.hash }}</h1>
            <img src="/media/tickets/{{ ticket.hash }}.jpg" />
            <a href="{% url 'oldcore:download_ticket' ticket.hash %}">Descargar como Archivo</a> 
            <h1>------------------------------------------</h1>
        </div>
        {% endfor %}
    </body>
</html>

deliriummcore/oldcore/templates/oldcore/index.html
{% extends "oldcore/base.html"%}

{% block title %}OldCore - DLMM{% endblock %}

{% block content %}



<div class="container-fluid">
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        <h1>OldCORE</h1>
        <p>Hola {{ user.username }}!</p>
        
        <div class="card shadow mb-4 ">
            <div class="card-body ">
                <ul class="nav justify-content-center">
                  
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'oldcore:create_request' %}">Crear Request</a>
                    </li>
                    <a class="nav-link" href="{% url 'oldcore:my_requests' %}">Ver mis Requests</a>
                    </li>
                </ul>
            </div>
        </div>

    </div>

    
</div>



{% endblock %}

deliriummcore/oldcore/templates/oldcore/log_websocket.html
{% extends "oldcore/base.html"%}

{% block title %}Log WebSocket - DLMM{% endblock %}

{% block content %}



    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/event/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
            document.querySelector('#chat-log').scrollTop = document.querySelector('#chat-log').scrollHeight;
        };

        chatSocket.onclose = function(e) {
            console.error('Event socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>

{% endblock %}

deliriummcore/oldcore/templates/oldcore/rp_check_main.html
{% extends "oldcore/base.html"%}
{% load static %}
{% block title %}RP Check - DLMM{% endblock %}

{% block head %}

<script type="text/javascript">
    $(document).ready( function () {
        $('#lista1').DataTable({
                "search": {
                  "caseInsensitive": true
                }
            }
        ) 
    } );
</script>
{% endblock head %}


{% block content %}



<div class="container-fluid">

    <div class="py-2">
        <a href="{% url 'oldcore:admin_index' %}"><button class="btn btn-dark">Regresar</button></a>
    </div>
    
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h1>RP Check</h1>
        <p>{{ user_selected.username }}</p>

        <div class="container mt-3">
            <h2>Requests - {{ user_selected.username }}</h2>
        </div>
        <div class="container-fluid">
            <div class="table-responsive">
                <table id="lista1" class="table table-striped ">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Status</th>
                            <th>Tickets</th>
                            <th>Total</th>
                            <th>Fase</th>
                            <th>RP</th>
                            <th>Cliente</th>
                            <th>Método</th>
                            <th>CashPay</th>
                            <th>View</th>
                            <th>Created</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for req in requests %}
                        {% if req.status == "AP" %}
                        <tr class="table-success">

                        {% elif req.status == "PE" %}
                        <tr class="table-warning">
                        {% else %}
                        <tr>
                        {% endif %}
                        
                            <th>{{ req.id }}</th>
                            <th>{{ req.get_status_display}}</th>
                            <th>{{ req.q_tickets }}</th>
                            <th>{{ req.total }}$</th>
                            <th>{{ req.fase.name }} - {{req.fase.price}}$</th>
                            <th>{{ req.user.username }}</th>
                            <th>{{ req.client }}</th>
                            <th>{{ req.payment_method }}</th>
                            <th>{{ req.cash_pay }}</th>
                            <th><a href="{% url 'oldcore:request_view' req.id %}"><img src="{% static 'core/icons/square_and_pencil_black.svg' %}" alt="View" height=20 width=20></a></th>
                            <th>{{ req.created }}</th>
                        </tr>
                        {% endfor %}

                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Status</th>
                            <th>Tickets</th>
                            <th>Total</th>
                            <th>Fase</th>
                            <th>RP</th>
                            <th>Cliente</th>
                            <th>Método</th>
                            <th>CashPay</th>
                            <th>View</th>
                            <th>Created</th>
        
                        </tr>
                    </tfoot>
                </table>
            </div>

        </div>
    
    
    </div>
    
</div>



{% endblock %}

deliriummcore/oldcore/templates/oldcore/rp_check_select.html
{% extends "oldcore/base.html"%}

{% block title %}RP Check - DLMM{% endblock %}

{% block content %}

<div class="container-fluid">

    
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h1>RP Check</h1>
        <p>Seleccionar Usuario</p>



        {% if users %}
        <form class="pt-3" action="{% url 'oldcore:rp_check_select' %}" method="POST" >
            {% csrf_token %}

            <div class="mb-3">
                <select class="form-select" name="us" aria-label="Select ORG">
                    <option disabled selected>Elige Usuario..</option>
                    {% for u in users %}
                    <option value="{{ u.user.username }}">{{ u.user.username }}</option>
                    {% endfor %}

                </select>
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Seleccionar</button>
            </div>
        {% endif %}

            




    </div>
    
</div>



{% endblock %}

deliriummcore/oldcore/templates/oldcore/ticket_export.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'oldcore/style_layout1.css' %}">
        
        {% block head %}
        {% endblock %}

        <link rel="stylesheet" type="text/css" href="{% static 'oldcore/ticket.css' %}">

        <meta name="imgkit-format" content="jpg"/>
        <meta name="imgkit-orientation" content="Landscape"/>
        
    </head>
    <body>
        
        <div class="container">
            <div class="row">
                <h1>NOVEMBER 5</h1>
            </div>
                <img id="qr"src="https://chart.googleapis.com/chart?chs=150x150&cht=qr&chl={{ hash }}" alt="Tu boleto" width="200" height="200">
                <h6>{{ hash }}</h6>
            </div>
        </div>
    </body>
</html>