deliriummcore/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'ticket', views.TicketViewSet)
router.register(r'entrada', views.EntradaViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls'))
]

deliriummcore/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),


    #TOOLS
    path("tools/", views.tools, name="tools"),



    #TOOL - 1 - ORGMAIN - INDEX
    path("tools/1/", views.tool_orgmain_index, name="tool_orgmain_index"),
    path("tools/1/lista", views.tool_orgmain_lista, name="tool_orgmain_lista"),
    path("tools/1/add_org", views.tool_orgmain_add_org, name="tool_orgmain_add_org"),

    #TOOL - 2 - BRANDMAIN - INDEX
    path("tools/2/", views.tool_brandmain_index, name="tool_brandmain_index"),





    
]

deliriummcore/deliriummcore/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("core/", include("core.urls")),
    path("events/", include("events.urls")),
    path("oldcore/", include("oldcore.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

deliriummcore/core/models.py
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
 

class CoreTool(models.Model):

    name = models.CharField(max_length=30)

    verbosename = models.CharField(max_length=30)

    description = models.CharField(max_length=100)

    admin = models.BooleanField(default=False)
    mod = models.BooleanField(default=False)
    org = models.BooleanField(default=False)
    staff = models.BooleanField(default=False)
    rp = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name
    


class CoreOrg(models.Model):
    account = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return "Org: " + self.name


class CoreBrand(models.Model):
    org = models.ForeignKey(CoreOrg, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300)

    username = models.CharField(max_length=30)

    logo = models.FileField(upload_to='uploads/brands/logos', blank=True)

    def __str__(self) -> str:
        return "Brand: " + self.name







#User class
# class UserCore(models.Model):

#     user = models.OneToOneField(User, on_delete=models.CASCADE)



#     def __str__(self) -> str:
#         return str(self.user)

#     class Meta:

#         permissions = (
#             ("can_view_admin", "To see admin pages"),
#             ("can_view_mod", "To see mod pages"),
#             ("can_view_", "To see admin pages"),
#             ("can_view_staff", "To see staff pages"),
#             ("can_view_rp", "To see rp PAGES"),
#         )

#  #Add other custom permissions according to need.



    

deliriummcore/core/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from core.models import CoreTool, CoreOrg, CoreBrand
from core.methods import checkCoreOrgAdd, getCoreOrgAccount, checkCoreOrgUser, getCoreOrgID
from main.methods import checkUser, getUser, checkCoreAccess, getCoreRole, checkCoreToolAccess, changeRole

from main.models import Profile

# CORE MAIN - INDEX PAGE
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        return render(request, 'core/index.html')


# CORE MAIN - DASHBOARD - SEGÚN ROL :)
def dashboard(request):
    # CHECK LOGIN
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    
    # CHECK CORE ACCESS
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))
    
    # CHECKS COMPLETE
    else:
        role = getCoreRole(request.user)

        #If RP
        if role == 2:
            # RP Dashboard render
            return render(request, 'core/admin/admin_dashboard.html', {
                "tools": CoreTool.objects.filter(admin=True),
            })
        #If ADMIN
        elif role == 6:
            # Admin Dashboard render
            return render(request, 'core/admin/admin_dashboard.html', {
                "tools": CoreTool.objects.filter(admin=True),
            })

        #Default Dashboard render
        return render(request, 'core/admin/admin_dashboard.html', {
                "tools": CoreTool.objects.filter(admin=True),
            })


# TOOLS - DEFAULT REDIRECT

def tools(request):
    # CHECK LOGIN
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    
    # CHECK CORE ACCESS
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))
    
    else:
        return HttpResponseRedirect(reverse("core:index"))

#-------------------------#

# Tools - 1 - Administrar Organizadores - #tool_orgmain

# INDEX TOOL
def tool_orgmain_index(request):
    # CHECK LOGIN
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    
    # CHECK CORE ACCESS
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))
    # CHECKS COMPLETE
    else:
        #Check if TOOL Register
        tool = get_object_or_404(CoreTool, name="tool_orgmain")

        #Check TOOL Access
        if checkCoreToolAccess(request.user, tool.id):

            #Default
            return render(request, 'core/tools/orgmain/index.html', {
                "tool": get_object_or_404(CoreTool, id=1),
            })
        #Not Access TOOL
        return HttpResponseRedirect(reverse("main:home"))

# LISTA TOOL
def tool_orgmain_lista(request):
    # CHECK LOGIN
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    
    # CHECK CORE ACCESS
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))
    # CHECKS COMPLETE
    else:
        #Check if TOOL Register
        tool = get_object_or_404(CoreTool, name="tool_orgmain")

        #Check TOOL Access
        if checkCoreToolAccess(request.user, tool.id):

            #Default
            return render(request, 'core/tools/orgmain/org_lista.html', {
                "tool": get_object_or_404(CoreTool, id=1),
                "orgs": CoreOrg.objects.all(),
            })
        #Not Access TOOL
        return HttpResponseRedirect(reverse("main:home"))

# AGREGAR ORGANIZADOR TOOL
def tool_orgmain_add_org(request):
    # CHECK LOGIN
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    
    # CHECK CORE ACCESS
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))
    # CHECKS COMPLETE
    else:
        #Check if TOOL Register
        tool = get_object_or_404(CoreTool, name="tool_orgmain")

        #Check TOOL Access
        if checkCoreToolAccess(request.user, tool.id):

            #POST REQUEST // ADD ORG
            if request.POST:

                #Checar Usuario si existe
                if getUser(str(request.POST["user"])):
                    
                    user = getUser(str(request.POST["user"]))

                    checkOrg = checkCoreOrgAdd(user)
                    if checkOrg[0] == True:
                        return render(request, 'core/tools/orgmain/org_add_org.html', {
                            "tool": get_object_or_404(CoreTool, id=1),
                            "message": checkOrg[1],
                            "message_type": "danger"
                        })
                    
                    name = ""
                    if request.POST["name"] == "":
                        name = "default"
                    else:
                        name = request.POST["name"]
                    # Cambiar Role en PROFILE MODEL
                    changeRole(user, roleint=4)
                
                    # Crear CoreOrg MODEL
                    CoreOrg.objects.create(account=user, name=name)


                    #Return Cambio completo con alerta
                    return render(request, 'core/tools/orgmain/org_add_org.html', {
                        "tool": get_object_or_404(CoreTool, id=1),
                        "message": "Organizador Agregado!",
                        "message_type": "success"
                        })
                # El usuario no existe
                else:
                    #Return usuario no existe con alerta danger
                    return render(request, 'core/tools/orgmain/org_add_org.html', {
                        "tool": get_object_or_404(CoreTool, id=1),
                        "message": "Usuario no encontrado!",
                        "message_type": "danger"
                        })

            #Default
            return render(request, 'core/tools/orgmain/org_add_org.html', {
                "tool": get_object_or_404(CoreTool, id=1),
            })
        #Not Access TOOL
        return HttpResponseRedirect(reverse("main:home"))

#-------------------------#

# Tools - 2 - Administrar Tus Marcas - #tool_brandmain


############# CAMBIAR - VER NOTION

# INDEX TOOL
def tool_brandmain_index(request):
    # CHECK LOGIN
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    
    # CHECK CORE ACCESS
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))
    # CHECKS COMPLETE
    else:
        #Check if TOOL Register
        tool = get_object_or_404(CoreTool, name="tool_brandmain")

        #Check TOOL Access
        if checkCoreToolAccess(request.user, tool.id):
            role = getCoreRole(request.user)
            
            # If Admin ROL 
            if role == 6:
                if request.method == "POST":
                    if request.POST["org"]:
                        org = getCoreOrgID(request.POST["org"])

                        checkOrgUser = checkCoreOrgUser(org.account)
                        #ORG NO PROBLEMS
                        if checkOrgUser[0] == True:
                            return render(request, 'core/tools/brandmain/index.html', {
                                "tool": get_object_or_404(CoreTool, id=2),
                                "brands": CoreBrand.objects.filter(org=getCoreOrgAccount(org.account))
                        })
                    
                        #ORG Problems
                        else:
                            return render(request, 'core/tools/brandmain/index.html', {
                                    "tool": get_object_or_404(CoreTool, id=1),
                                    "message": checkOrgUser[1],
                                    "message_type": "danger"
                                })
                
                return render(request, 'core/tools/brandmain/select_org_admin.html', {
                    "tool": get_object_or_404(CoreTool, id=2),
                    "orgs": CoreOrg.objects.all()
                })

            
            # If Org ROL
            elif role == 4:

                checkOrgUser = checkCoreOrgUser(request.user)
                #ORG NO PROBLEMS
                if checkOrgUser[0] == True:
                    return render(request, 'core/tools/brandmain/index.html', {
                        "tool": get_object_or_404(CoreTool, id=2),
                        "brands": CoreBrand.objects.filter(org=getCoreOrgAccount(request.user))
                })
                
                #ORG Problems
                else:
                    return render(request, 'core/tools/brandmain/index.html', {
                            "tool": get_object_or_404(CoreTool, id=1),
                            "message": checkOrgUser[1],
                            "message_type": "danger"
                        })


            #Default
            return render(request, 'core/tools/brandmain/index.html', {
                "tool": get_object_or_404(CoreTool, id=2),
            })
        #Not Access TOOL
        return HttpResponseRedirect(reverse("main:home"))

#-------------------------#

deliriummcore/core/templates/core/tools/orgmain/index.html
{% extends "core/base.html"%}

{% block title %}{{ tool.verbosename }}{% endblock %}

{% block content %}


<div class="container-fluid">
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h1>{{ tool.verbosename }}</h1>
        <p>Hola {{ user.username }}!</p>



          <div class="card shadow mb-4">
            <div class="card-body ">
                <ul class="nav justify-content-center">
                    <li class="nav-item border-0">
                        <a class="nav-link" href="{% url 'core:tool_orgmain_lista' %}">Lista de Organizadores</a>
                    </li>
                    <a class="nav-link" href="{% url 'core:tool_orgmain_add_org' %}">Agregar Organizador</a>
                    </li>
                    <li class="nav-item border-0">
                        <a class="nav-link" href="{% url 'core:tool_orgmain_add_org' %}">Borrar Organizador</a>
                    </li>
                    <li class="nav-item border-0">
                        <a class="nav-link" href="{% url 'core:tool_orgmain_add_org' %}">Borrar Organizador</a>
                    </li>
        
                </ul>
            </div>
        </div>


    

        

    </div>

    
</div>



{% endblock %}

deliriummcore/core/templates/core/tools/orgmain/org_add_org.html
{% extends "core/base.html"%}

{% block title %}Agregar Organizador{% endblock %}

{% block content %}

<div class="container-fluid">

    <div class="py-2">
        <a href="{% url 'core:tool_orgmain_index' %}"><button class="btn btn-dark">Regresar</button></a>
    </div>
    
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h1>{{ tool.verbosename }}</h1>
        <p>Agregar Organizador</p>


        <div class="container mt-3">
            <h2>Agregar Organizador</h2>
            <div class="container">
                <form action="{% url 'core:tool_orgmain_add_org' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Nombre de Usuario</span>
                        <input type="text" name="user" class="form-control" placeholder="Usuario" aria-label="Usuario" aria-describedby="basic-addon1">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Nombre</span>
                        <input type="text" name="name" class="form-control" placeholder="Nombre" aria-label="Nombre" aria-describedby="basic-addon1">
                    </div>
                    <button type="submit" class="btn btn-primary text-center">Agregar</button>
                </form>
            </div>
        </div>

    </div>
    
</div>



{% endblock %}

deliriummcore/core/templates/core/tools/orgmain/org_lista.html
{% extends "core/base.html"%}

{% block title %}Lista de Organizadores{% endblock %}

{% block content %}

<div class="container-fluid">

    <div class="py-2">
        <a href="{% url 'core:tool_orgmain_index' %}"><button class="btn btn-dark">Regresar</button></a>
    </div>
    
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h1>{{ tool.verbosename }}</h1>
        <p>Lista de Organizadores</p>

        <div class="container mt-3">
            <h2>Todos los Organizadores</h2>
        </div>
        <div class="container">
            {% if orgs %}
            {% for org in orgs %}
             <p>{{ org.name }}</p>
            {% endfor %}
            {% endif %}
        </div>

    </div>
    
</div>



{% endblock %}