deliriummcore/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'ticket', views.TicketViewSet)
router.register(r'entrada', views.EntradaViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls'))
]

deliriummcore/deliriummcore/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("core/", include("core.urls")),
    path("events/", include("events.urls")),
    path("oldcore/", include("oldcore.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

deliriummcore/oldcore/urls.py
from django.urls import path

from . import views

app_name = 'oldcore'

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),

    path("a/", views.admin_index, name="admin_index"),
    path("a/lista_requests/", views.admin_lista_requests, name="admin_lista_requests"),
    path("a/rp_check/select", views.rp_check_select, name="rp_check_select"),
    path("a/rp_check/<str:username>", views.rp_check_main, name="rp_check_main"),
    path("a/cash/", views.cash_index, name="cash_index"),
    path("a/cash/cashpaytoggle/<int:id>", views.cashpaytoggle, name="cashpaytoggle"),

    path('a/log_websocket/<str:room_name>/', views.log_websocket, name='log_websocket'),

    path("r/new/", views.create_request, name="create_request"),
    path("r/new/create", views.new_ticket_request, name="new_ticket_request"),
    path("r/<int:requestid>", views.request_view, name="request_view"),

    path("r/my_requests", views.my_requests, name="my_requests"),
    path("r/my_requests/list", views.lista_requests, name="lista_requests"),

    path("r/<int:requestid>/delete", views.delete_ticket_request, name="delete_ticket_request"),
    path("a/<int:requestid>", views.admin_request_view, name="admin_request_view"),
    path("a/<int:requestid>/ap", views.aprobar_request, name="aprobar_request"),
    path("a/<int:requestid>/re", views.rechazar_request, name="rechazar_request"),
    path("a/<int:requestid>/ar", views.archivar_request, name="archivar_request"),
    path("a/<int:requestid>/as", views.asignar_request, name="asignar_request"),
    path("t/export/<str:hash>", views.temp_ticket_export, name="temp_ticket_export"),
    path("t/requestall/<str:requestid>", views.image_tickets, name="image_tickets"),
    path("t/image/<str:hash>", views.image_ticket, name="image_ticket"),
    path("t/download/<str:tickethash>", views.download_ticket, name="download_ticket"),
]

deliriummcore/oldcore/models.py
from datetime import datetime
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Seller(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    
    class Meta:
         
        permissions = (
            ("can_view_admin", "To see admin pages"),
            ("can_view_staff", "To see staff pages"),
            ("can_view_rp", "To see rp PAGES"),
        )


class Event(models.Model):
    name = models.CharField(verbose_name="Nombre", max_length=30)
    datetime = models.DateTimeField()
    locationmapslink = models.CharField(max_length=300, verbose_name="Google Maps Link", blank=True)

    STATUS = ( 
        ("AN", "Anunciado"), 
        ("EV", "En Venta"), 
        ("VT", "Venta Terminada"), 
        ("AR", "Archivado"), 
    ) 
    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default='AN',
    )

    def __str__(self) -> str:
        return self.name

class Fase(models.Model):
    name = models.CharField(verbose_name="Nombre de Fase", max_length=20)
    event = models.ForeignKey(verbose_name="Evento", to=Event, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name="Precio")
    is_active = models.BooleanField(default=False)
    q_sells = models.IntegerField(verbose_name="Ventas", default=0)

    def __str__(self):
        return "Fase - " + self.name + " - " + self.event.name
    


class TicketRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    seller = models.ForeignKey(to=Seller, on_delete=models.CASCADE)
    event = models.ForeignKey(to=Event, on_delete=models.CASCADE)
    context = models.CharField(max_length=300, blank=True)
    q_tickets = models.IntegerField(verbose_name="Tickets")
    reference = models.CharField(max_length=150, default="none")
    client = models.CharField(max_length=50, default="none")
    fase = models.ForeignKey(Fase, on_delete=models.CASCADE)
    total = models.IntegerField(verbose_name="Total", default="0")
    created = models.DateTimeField(auto_now=True)
    staff_asigned = models.CharField(max_length=30, default="none")
    comprobante = models.FileField(upload_to='uploads/comprobantes/quimera/', blank=True)

    PAYMENTS = ( 
        ("CASH", "Efectivo"), 
        ("TRANSFER", "Transferencía"), 
        ("DEPOSIT", "Deposíto"), 
    ) 
    payment_method = models.CharField(
        max_length=20,
        choices=PAYMENTS,
        default='CASH',
    )

    STATUS = ( 
        ("PE", "Pendiente"), 
        ("RE", "Rechazado"), 
        ("AP", "Aprobado"), 
        ("AR", "Archivado"), 
    ) 
    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default='PE',
    )

    cash_pay = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return "#" + str(self.pk) + " - " + self.user.username + " " + self.status 



class Ticket(models.Model):

    hash = models.CharField(primary_key=True, verbose_name="Hash Id", max_length=200)
    client = models.CharField(max_length=50, default="none")
    ticketrequest = models.ForeignKey(TicketRequest, on_delete=models.CASCADE)


    user = models.ForeignKey(User, on_delete=models.CASCADE)
    seller = models.ForeignKey(to=Seller, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    fase = models.ForeignKey(Fase, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name="Price")

    status_export = models.BooleanField(default=True)

    use = models.BooleanField(default=False)
    
    def __str__(self):
        return "%s %s" % (self.hash, self.ticketrequest.pk)

class CommentTicketRequest(models.Model):
    ticketrequest = models.ForeignKey(TicketRequest, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    text = models.CharField(max_length=600)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)


class RegToken(models.Model):
    token = models.CharField(max_length=20)

class Entrada(models.Model):
    name = models.CharField(max_length=40, default="name_default")
    price = models.IntegerField(verbose_name="Price")
    created = models.DateTimeField(auto_now=True)
    isCortesia = models.BooleanField(default=False)
    

    def __str__(self):
        return str(self.price) + "$ - " + str(self.isCortesia)
    
    

deliriummcore/oldcore/views.py
import os
from webbrowser import get
import imgkit
import mimetypes

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from main.methods import checkCoreAccess, getCoreRole
from oldcore.models import Event, TicketRequest, Ticket, Seller, Fase, Entrada
from django.conf import settings
from oldcore.methods import checkSeller
from django.db.models import Q
from django.contrib.auth.models import User


from hashlib import md5, sha256

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        checkSeller(request.user)
        return render(request, 'oldcore/index.html')

def dashboard(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        checkSeller(request.user)

        requests_ap = TicketRequest.objects.filter(Q(user=request.user) &  Q(status="AP"))
        ap_cash = 0
        for ticket in requests_ap:
            ap_cash = ap_cash + ticket.total


        requests_cash = TicketRequest.objects.filter(Q(payment_method="CASH") &  Q(status="AP") & Q(user=request.user))
        all_cash = 0
        requests_debt = requests_cash.filter(cash_pay=False)
        debt_cash = 0

        for ticket in requests_cash:
            all_cash = all_cash + ticket.total

        for ticket in requests_debt:
            debt_cash = debt_cash + ticket.total
        
        

        return render(request, 'oldcore/dashboard.html', {
            "requests_cash": TicketRequest.objects.filter(user=request.user, payment_method="CASH"),
            "all_cash": all_cash,
            "debt_cash": debt_cash,
            "paid_cash": all_cash - debt_cash,
            "ap_cash": ap_cash,
            "boletos": len(Ticket.objects.filter(user=request.user)),
            "comision": int(ap_cash*0.1),

            

        })

def admin_index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        checkSeller(request.user)
        if getCoreRole(request.user) == 6 or getCoreRole(request.user) == 5:

            requests_ap = TicketRequest.objects.filter(Q(user=request.user) &  Q(status="AP"))
            ap_cash = 0
            for ticket in requests_ap:
                ap_cash = ap_cash + ticket.total


            requests_cash = TicketRequest.objects.filter(Q(payment_method="CASH") &  Q(status="AP") & Q(user=request.user))
            all_cash = 0
            requests_debt = requests_cash.filter(cash_pay=False)
            debt_cash = 0

            for ticket in requests_cash:
                all_cash = all_cash + ticket.total

            for ticket in requests_debt:
                debt_cash = debt_cash + ticket.total

            entradas = Entrada.objects.all()
            entradas_total = 0

            for entrada in entradas:
                entradas_total = entradas_total + entrada.price
            

            return render(request, 'oldcore/admin_index.html', {
                "requests_cash": TicketRequest.objects.filter(user=request.user, payment_method="CASH"),
                "all_cash": all_cash,
                "debt_cash": debt_cash,
                "paid_cash": all_cash - debt_cash,
                "ap_cash": ap_cash,
                "boletos": len(Ticket.objects.filter(user=request.user)),
                "comision": int(ap_cash*0.1),
                "entradas_total": entradas_total

                

            })
        else:
            return HttpResponseRedirect(reverse("main:home"))

def rp_check_select(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        checkSeller(request.user)
        if getCoreRole(request.user) == 6 or getCoreRole(request.user) == 5:
            if request.method == "POST":
                if request.POST["us"]:
                    username = request.POST["us"]
                    return HttpResponseRedirect(reverse("oldcore:rp_check_main", args=(username,)))
            
            else:
                return render(request, 'oldcore/rp_check_select.html', {
                    "users": Seller.objects.all(),
                })


        else:
            return HttpResponseRedirect(reverse("main:home"))

def rp_check_main(request, username):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        checkSeller(request.user)
        if getCoreRole(request.user) == 6 or getCoreRole(request.user) == 5:
            user_selected = get_object_or_404(User, username=username)

            return render(request, 'oldcore/rp_check_main.html', {
                    "requests": TicketRequest.objects.filter(user=user_selected),
                    "user_selected": user_selected,
                })
        else:
            return HttpResponseRedirect(reverse("main:home"))   

def lista_requests(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        checkSeller(request.user)

        user_selected = get_object_or_404(User, username=request.user)

        return render(request, 'oldcore/tools/ticketsrequest/lista_requests.html', {
                "requests": TicketRequest.objects.filter(user=user_selected),
                "user_selected": user_selected,
                })   

def admin_lista_requests(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        checkSeller(request.user)
        if getCoreRole(request.user) == 6 or getCoreRole(request.user) == 5:

            requests = TicketRequest.objects.all()
            requests_aproved = TicketRequest.objects.filter(status="AP")
            ticketcount_aproved = 0

            for req in requests_aproved:
                ticketcount_aproved = ticketcount_aproved + req.q_tickets 

            requests_cash_aproved = TicketRequest.objects.filter(Q(payment_method="CASH") & Q(status="AP"))
            ticketcount_cash_aproved= 0

            for req in requests_cash_aproved:
                ticketcount_cash_aproved = ticketcount_cash_aproved + req.q_tickets 

            requests_trans_aproved = TicketRequest.objects.filter(Q(payment_method="TRANSFER") & Q(status="AP"))
            ticketcount_trans_aproved= 0

            for req in requests_trans_aproved:
                ticketcount_trans_aproved = ticketcount_trans_aproved + req.q_tickets 

            requests_dep_aproved = TicketRequest.objects.filter(Q(payment_method="DEPOSIT") & Q(status="AP"))
            ticketcount_dep_aproved= 0

            for req in requests_dep_aproved:
                ticketcount_dep_aproved = ticketcount_dep_aproved + req.q_tickets 

            entrada_total = Entrada.objects.all()
            totale = 0

            for e in entrada_total:
                totale = totale + e.price

            cash_total = 0

            for req in requests:
                cash_total = cash_total + req.total


            return render(request, 'oldcore/tools/ticketsrequest/admin_lista_requests.html', {
                "requests": requests,
                "ticketcount_aproved": ticketcount_aproved,
                "ticketcount_cash_aproved": ticketcount_cash_aproved,
                "ticketcount_trans_aproved": ticketcount_trans_aproved,
                "ticketcount_dep_aproved": ticketcount_dep_aproved,
                "totale": totale,
                "cash_total": cash_total,
                
            })
        else:
            return HttpResponseRedirect(reverse("main:home"))


def my_requests(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:    
        return render(request, "oldcore/tools/ticketsrequest/my_requests.html",{
            "ticketspe": request.user.ticketrequest_set.all().filter(status="PE"),
            "ticketsap": request.user.ticketrequest_set.all().filter(status="AP"),
            "ticketsre": request.user.ticketrequest_set.all().filter(status="RE"),

        })

def create_request(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        event_on_sell = get_object_or_404(Event, status="EV")
        fase = event_on_sell.fase_set.get(is_active=True)
        return render(request, "oldcore/tools/ticketsrequest/create_request.html", {
            "event": event_on_sell,
            "fase": fase,
        })

def new_ticket_request(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    elif not checkCoreAccess(request.user):
        return HttpResponseRedirect(reverse("main:home"))

    else:
        event = get_object_or_404(Event, status="EV")

deliriummcore/oldcore/templates/oldcore/tools/ticketsrequest/admin_request_view.html
{% extends "oldcore/base.html"%}

{% block title %}Admin Request #{{ requestid }} - DLMM{% endblock %}

{% block content %}


<h1>Tickets - Admin</h1>



<div class="card shadow mb-4 ">
    <div class="card-body ">
        <ul class="nav justify-content-center">
            <li class="nav-item border-0">
                <a class="nav-link" href="{% url 'oldcore:aprobar_request' requestid %}">Aprobar</a>
            </li>
            <li class="nav-item border-0">
                <a class="nav-link" href="{% url 'oldcore:rechazar_request' requestid %}">Rechazar</a>
            </li>
            <li class="nav-item border-0">
                <a class="nav-link" href="{% url 'oldcore:archivar_request' requestid %}">Archivar</a>
            </li>
            <li class="nav-item border-0">
                <a class="nav-link" href="{% url 'oldcore:asignar_request' requestid %}">Asignar</a>
            </li>

        </ul>
    </div>
</div>

<!-- Card 1 -->
    <div class="card mb-4">
        <!-- Card Header -->
        <div class="card-header py-3">
            <div class="row justify-content-between">
                <div class="col-xl-4 col-md-6">
                    <h6 class="m-0 text-primary">Ticket Request #{{ requestid }} <mark>Estado: {{ status_display }}</mark></h6>
                </div>
                <div class="col-xl-5 col-md-6">
                    <div class="text-end">
                        <a href="{% url 'oldcore:admin_index' %}"><button type="button" class="btn btn-success btn-sm">Admin Index</button></a>
                        
                        <a href="{% url 'oldcore:request_view' requestid %}"><button type="button" class="btn btn-secondary btn-sm">Regresar a Request</button></a>
                        <a href="{% url 'oldcore:delete_ticket_request' requestid %}"><button type="button" class="btn btn-danger btn-sm">Borrar Request</button></a>
                        
                    </div>
                </div>
            </div>
        </div>

<!-- Part -->

<div class="row">
    {% comment %} col-xl-4 tamaño main {% endcomment %}
<div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary mb-1">
                        Información del evento</div>
                    <div class="p mb-0 text-gray-800">
                        {{ ticketrequest.event.name }}
                    </div>
                    <div class="p mb-0 text-gray-800">
                        {{ ticketrequest.event.datetime }}
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Part -->

<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary mb-1">
                        Tickets</div>
                    <div class="p mb-0 text-gray-800">
                        Cantidad: {{  ticketrequest.q_tickets }}
                    </div>
                    <div class="p mb-0 text-gray-800">
                        Total: {{  ticketrequest.total }} MXN
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Part -->

<div class="col-xl-5 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary mb-1">
                        Pago - {{ ticketrequest.get_payment_method_display }}</div>
                    {% if ticketrequest.payment_method == "CASH" %}
                    <div class="p mb-0 text-gray-800">
                        Comprobante: Efectivo
                    </div>
                    {% endif %}
                    {% if not ticketrequest.payment_method == "CASH" %}
                    <div class="p mb-0 text-gray-800">
                        Comprobante: <a href="/media/{{ticketrequest.comprobante}}" target="_blank" rel="noopener noreferrer">Ver Comprobante</a>
                    </div>
                   {% endif %}
                    <div class="p mb-0 text-gray-800">
                        Referencía: {{  ticketrequest.reference }}
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Part -->

<div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary mb-1">
                        Request</div>
                    <div class="p mb-0 text-gray-800">
                        Cliente: {{ ticketrequest.client }}
                    </div>
                    <div class="p mb-0 text-gray-800">
                        Request: {{ ticketrequest.created }}
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Part -->

<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary mb-1">
                        Request</div>
                    <div class="p mb-0 text-gray-800">
                        Hecha por: @{{ ticketrequest.user.username }}
                    </div>
                    {% if ticketrequest.staff_asigned != "none" %}
                    <div class="p mb-0 text-gray-800">
                        Staff asignado: @{{ ticketrequest.staff_asigned }}
                    </div>
                    {% endif %}
                </div>
                <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Part -->
{% if ticketrequest.status == "AP" or ticketrequest.status == "AR" %}
<div class="col-xl-4 col-md-6 mb-4">
<div class="card border-left-primary shadow h-100 py-2">
<div class="card-body">
    <div class="row no-gutters align-items-center">
        <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary mb-1">
                Tickets - <a href="{% url 'oldcore:image_tickets' requestid %}">Guardar en Imagen</a></div>
            {% for ticket in ticketslist %}
            <div class="p mb-0 text-gray-800">
                <a href="{% url 'oldcore:image_ticket' ticket.hash %}">Ticket {{ forloop.counter }} - #{{ ticket.hash |slice:':-15' }}...</a> 
            </div>
            {% endfor %}
        </div>
        <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
        </div>
    </div>
</div>
</div>
</div>
{% endif %}

<!-- Descripción Area -->
</div>
<div class="card-header py-3">
<div class="text-start m-0 font-weight-bold text-primary">
    Comentario
</div>
</div>
<div class="card-body">
    <p class="mb-0">{{ ticketrequest.context}}</p>
</div>
</div>


<!-- For Loop Comments (conv) -->

{% if comments %}
<div class="card mb-4">
{% for comment in comments %}
     <div class="card-body">
            <h6>@{{ comment.user.username }}</h6>
            <p class="mb-0">{{ comment.text }}</p>
    </div>
{% endfor %}
    </div>
{% endif %}


{% endblock content %}

deliriummcore/oldcore/templates/oldcore/tools/ticketsrequest/delete_ticket_request.html
{% extends "oldcore/base.html"%}

{% block title %}Borrar Request - DLMM{% endblock %}

{% block content %}


<h3>¿Seguro de borrar el Ticket Request #{{ requestid }}?</h3>

<div class="container mt-4">
    <div class="row justify-content-start">
        <div class="col">
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" name="yes" class="btn btn-danger btn-lg" value="Si" />
            </form>
        </div>
        <div class="col">
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" name="not" class="btn btn-danger btn-lg" value="No" />
            </form>
        </div>
    </div>

</div>


{% endblock content %}

deliriummcore/oldcore/templates/oldcore/tools/ticketsrequest/my_requests.html
{% extends "oldcore/base.html"%}

{% block title %}OldCore - DLMM{% endblock %}

{% block content %}

<h1>Requests - <a href="{% url 'oldcore:lista_requests' %}">Ver en Lista</a> </h1>



<div class="row">

    {% for ticket in ticketspe %}
    
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="mb-1">
                            <a href="{% url 'oldcore:request_view' ticket.pk %}">Ticket Request #{{ ticket.pk }}</a></div>
                        <div class="mb-0">Estado: {{ ticket.get_status_display }}</div>
                        <div class="mb-0">Cliente: {{ ticket.client }}</div>
                        <div class="mb-0">Boletos: {{ ticket.q_tickets }} - Metodo: {{ ticket.get_payment_method_display }}</div>
                        {% if ticket.payment_method == "CASH" %}
                        <div class="mb-0">Efectivo entregado: {% if ticket.cash_pay == True %}Si{% else %}No{% endif %}</div>
                        {% endif %}
                        <div class="mb-0">Fase {{ ticket.fase.name }} - {{ ticket.fase.price }} MXN</div>
                        <div class="mb-0">Total: {{ ticket.total }} MXN</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

<div class="row">

    {% for ticket in ticketsap %}

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="mb-1">
                            <a href="{% url 'oldcore:request_view' ticket.pk %}">Ticket Request #{{ ticket.pk }}</a></div>
                        <div class="mb-0">Estado: {{ ticket.get_status_display }}</div>
                        <div class="mb-0">Cliente: {{ ticket.client }}</div>
                        <div class="mb-0">Boletos: {{ ticket.q_tickets }} - Metodo: {{ ticket.get_payment_method_display }}</div>
                        {% if ticket.payment_method == "CASH" %}
                        <div class="mb-0">Efectivo entregado: {% if ticket.cash_pay == True %}Si{% else %}No{% endif %}</div>
                        {% endif %}
                        <div class="mb-0">Fase {{ ticket.fase.name }} - {{ ticket.fase.price }} MXN</div>
                        <div class="mb-0">Total: {{ ticket.total }} MXN</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% endfor %}

</div>

<div class="row">

    {% for ticket in ticketsre %}

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="mb-1">
                            <a href="{% url 'oldcore:request_view' ticket.pk %}">Ticket Request #{{ ticket.pk }}</a></div>
                        <div class="mb-0">Estado: {{ ticket.get_status_display }}</div>
                        <div class="mb-0">Cliente: {{ ticket.client }}</div>
                        <div class="mb-0">Boletos: {{ ticket.q_tickets }} - Metodo: {{ ticket.get_payment_method_display }}</div>
                        {% if ticket.payment_method == "CASH" %}
                        <div class="mb-0">Efectivo entregado: {% if ticket.cash_pay == True %}Si{% else %}No{% endif %}</div>
                        {% endif %}
                        <div class="mb-0">Fase {{ ticket.fase.name }} - {{ ticket.fase.price }} MXN</div>
                        <div class="mb-0">Total: {{ ticket.total }} MXN</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% endfor %}

</div>


{% endblock %}