deliriummcore/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'ticket', views.TicketViewSet)
router.register(r'entrada', views.EntradaViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls'))
]

deliriummcore/deliriummcore/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("core/", include("core.urls")),
    path("events/", include("events.urls")),
    path("oldcore/", include("oldcore.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

deliriummcore/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path("<int:requestid>/", views.eventPage, name="eventpage"),
]

deliriummcore/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path("", views.landingPage, name="landingPage"),
    path("home/", views.home, name="home"),
    path("events/", views.events, name="events"),
    path("wallet/", views.wallet, name="wallet"),
    path("places/", views.places, name="places"),
    path("profile/", views.profile, name="profile"),

]

deliriummcore/oldcore/urls.py
from django.urls import path

from . import views

app_name = 'oldcore'

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),

    path("a/", views.admin_index, name="admin_index"),
    path("a/lista_requests/", views.admin_lista_requests, name="admin_lista_requests"),
    path("a/rp_check/select", views.rp_check_select, name="rp_check_select"),
    path("a/rp_check/<str:username>", views.rp_check_main, name="rp_check_main"),
    path("a/cash/", views.cash_index, name="cash_index"),
    path("a/cash/cashpaytoggle/<int:id>", views.cashpaytoggle, name="cashpaytoggle"),

    path('a/log_websocket/<str:room_name>/', views.log_websocket, name='log_websocket'),

    path("r/new/", views.create_request, name="create_request"),
    path("r/new/create", views.new_ticket_request, name="new_ticket_request"),
    path("r/<int:requestid>", views.request_view, name="request_view"),

    path("r/my_requests", views.my_requests, name="my_requests"),
    path("r/my_requests/list", views.lista_requests, name="lista_requests"),

    path("r/<int:requestid>/delete", views.delete_ticket_request, name="delete_ticket_request"),
    path("a/<int:requestid>", views.admin_request_view, name="admin_request_view"),
    path("a/<int:requestid>/ap", views.aprobar_request, name="aprobar_request"),
    path("a/<int:requestid>/re", views.rechazar_request, name="rechazar_request"),
    path("a/<int:requestid>/ar", views.archivar_request, name="archivar_request"),
    path("a/<int:requestid>/as", views.asignar_request, name="asignar_request"),
    path("t/export/<str:hash>", views.temp_ticket_export, name="temp_ticket_export"),
    path("t/requestall/<str:requestid>", views.image_tickets, name="image_tickets"),
    path("t/image/<str:hash>", views.image_ticket, name="image_ticket"),
    path("t/download/<str:tickethash>", views.download_ticket, name="download_ticket"),
]

deliriummcore/events/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.

deliriummcore/main/models.py
from email.policy import default
from django.db import models

from django.contrib.auth.models import User

class Profile(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    USER = 1
    PR = 2
    STAFF = 3
    ORG = 4
    MOD = 5
    ADMIN = 6
      
    ROLE_CHOICES = (
    (USER, 'Usuario'),
    (PR, 'RP'),
    (STAFF, 'Staff'),
    (ORG, 'Organizador'),
    (MOD, 'Moderador'),
    (ADMIN, 'Administrador'),
    )

    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True, default=1)

    def __str__(self) -> str:
        return str(self.user)


# You can create Role model separately and add ManyToMany if user has more than one role
      

deliriummcore/events/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def eventPage(request, requestid):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    else:
        return render(request, 'events/eventpage.html', {
            "requestid": requestid
        })

deliriummcore/main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Profile
from .methods import checkProfile

# Create your views here.


def landingPage(request):
    if not request.user.is_authenticated:
        return render(request, 'main/landingpage/index.html')
    else:
        return HttpResponseRedirect(reverse("main:home"))


def home(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    else:
        #Profile Model Creation MEJORAR!!!!!! CON URL UNICA DE CREACIÓN REDIRECT o CAMBIAR SISTEMA DE LOGIN A ANTIGUO Y AVANZADO
        checkProfile(request.user)
        

        #Render home base    
        return render(request, 'main/home.html')


def events(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    else:
        checkProfile(request.user)
        return render(request, 'main/events.html')


def places(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    else:
        checkProfile(request.user)
        return render(request, 'main/places.html')


def wallet(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    else:
        checkProfile(request.user)
        return render(request, 'main/wallet.html')


def profile(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
        
    else:
        checkProfile(request.user)
        return render(request, 'main/profile.html')

deliriummcore/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-md justify-content-center">

            <div class="container">

                <a href="/" class="navbar-brand d-auto w-50 me-auto">
                    DLMM Core</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
                    <ul class="navbar-nav w-100 justify-content-center">
                    
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:home' %}">
                                <img class="mx-auto d-none d-sm-block" src="{% static 'main/house_fill_white.svg'%}" width="20px" height="20px" alt="">
                                Inicio
                            </a>
                        </li>

                        <li class="nav-item active">
                            <a class="nav-link" href="">
                                <img class="mx-auto d-none d-sm-block" src="{% static 'main/calendar_white.svg'%}" width="20px" height="20px" alt="">
                                Eventos
                            </a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="">
                                <img class="mx-auto d-none d-sm-block" src="{% static 'main/mapping_and_ellipse_white.svg'%}" width="20px" height="20px" alt="">
                                Lugares
                        </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:wallet' %}">
                                <img class="mx-auto d-none d-sm-block" src="{% static 'main/wallet_pass_fill_white.svg'%}" width="20px" height="20px" alt="">
                                Wallet
                        </a>
                        </li>

                    </ul>
                    
                    <ul class="nav navbar-nav ms-auto w-100 justify-content-end">

                        <li class="nav-item">
                            <a class="nav-link" href="">
                                <img class="mx-auto d-none d-sm-block" src="{% static 'main/hammer_fill_white.svg'%}" width="20px" height="20px" alt="">
                                Arma tu Evento
                        </a>
                        </li>
                        {% comment %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Right</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Right</a>
                        </li>
                        {% endcomment %}

                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">

                            <img class="d-block d-sm-none" src="{% static 'main/person_crop_circle_white.svg'%}" width="20px" height="20px" alt="">

                            
                            <img class="mx-auto d-none d-sm-block" src="{% static 'main/person_crop_circle_white.svg'%}" width="20px" height="20px" alt="">

                            {{ user.username }}
                                


                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarScrollingDropdown">
                                <li><a class="dropdown-item" href="#">Perfil</a></li>
                                <li><a class="dropdown-item" href="#">Configuración</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'oldcore:index' %}">OldCore</a></li>
                                <li><a class="dropdown-item" href="#">Core</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    

    <div class="container">
        
        {% block content %}
        {% endblock %}
    </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

deliriummcore/main/templates/main/events.html
{% extends "main/base.html"%}
{% load static %}
{% block title %}Eventos{% endblock %}

{% block content %}



<div class="container-fluid">
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        <h1 class="pt-4">Eventos</h1>
        <img class="mx-auto d-none d-sm-block" src="{% static 'main/calendar_black.svg'%}" width="3%" height="auto" alt="">

        <div class="container mt-3">
          <h2>Todos los Eventos</h2>
        </div>

        <div class="container">

          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-xl-4">
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
          </div>
        </div>

    </div>

    
</div>



{% endblock %}

deliriummcore/main/templates/main/home.html
{% extends "main/base.html"%}

{% block title %}Home{% endblock %}

{% block content %}



<div class="container-fluid">
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        

        <h1>Bienvenido {{ user.username }}</h1>
        <p>Hi {{ user.username }}!</p>
        <a href="{% url 'oldcore:index' %}">
            <button type="button" class="btn btn-outline-primary">Entrar a oldCore</button>
        </a>

    </div>

    
</div>



{% endblock %}

deliriummcore/main/templates/main/places.html
{% extends "main/base.html"%}
{% load static %}
{% block title %}Lugares{% endblock %}

{% block content %}



<div class="container-fluid">
    <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
        <h1 class="pt-4">Lugares</h1>
        <img class="mx-auto d-none d-sm-block" src="{% static 'main/mapping_and_ellipse_black.svg'%}" width="3%" height="auto" alt="">

        <div class="container mt-3">
          <h2>Todos los Lugares</h2>
        </div>

        <div class="container">

          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-xl-4">
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
            <div class="col p-3">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Welcome To The Jungle</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Deliriumm - 25/03/2022</h6>
                  <img class="card-img-top" src="{% static 'main/testflyer1.jpg' %}" alt="Card image">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
            </div>
          </div>
        </div>

    </div>

    
</div>



{% endblock %}

deliriummcore/main/templates/main/profile.html
{% extends "main/base.html"%}

{% block title %}Perfil{% endblock %}

{% block content %}

<h1>Profile Page</h1>
<p>Hi {{ user.username }}!</p>


{% endblock %}

deliriummcore/main/templates/main/wallet.html
{% extends "main/base.html"%}

{% block title %}Wallet{% endblock %}

{% block content %}

<div class="container-fluid">
    <h1>Wallet</h1>
    <p>Hi {{ user.username }}!</p>
</div>




{% endblock %}